# Training parameters
batch_size: 64
learning_rate: 1e-4
num_epochs: 100
sequence_length: 20
max_ep_len: 4096

# Model parameters
hidden_size: 256
n_layer: 4
n_head: 4

# Data parameters
data_dir: 'path/to/your/data/directory'
chunk_size: 5

# Wandb configuration
wandb:
  project: "decision-transformer"
