# Training parameters
batch_size: 64
learning_rate: 1e-4
num_epochs: 100
sequence_length: 5
max_ep_len: 4096

# Model parameters
hidden_size: 128
n_layer: 2
n_head: 4

# Data parameters
data_dir: data/demos/processed
chunk_size: 5

# Wandb configuration
wandb:
  project: 'decision-transformer'
